### PR TITLE
Multi argument environment

### PR DESCRIPTION
**Pull request by sebastianhaas**
As discussed in https://github.com/JelteF/PyLaTeX/issues/71.

Just the multiple argument support plus an example on how to represent new LaTeX commands and environment using this beautiful library :)

### CODE REVIEW

**Comment by JelteF** [comment]
One more thing, could you change it so that it uses Command directly?

**Comment by sebastianhaas** [comment]
I guess I could get it done today. However, I don't see why you would not want this branch rebased on master too?

**Comment by JelteF** [comment]
Rebasing was meant here as well, but my girlfriend needed some attention so I typed this quickly.

**Comment by sebastianhaas** [comment]
Alright.

**Comment by JelteF** [comment]
I have just merged this in so I'm closing this pull request.

**Pull request closed without merging**
