### PR TITLE
WIP: Adds support for quantities python package (latex: siunitx)

### PR DESCRIPTION
**Pull request by bjodah**
This is a friendly suggestion of adding support for [quantities](http://pythonhosted.org/quantities/).
This prototype uses [siunitx](https://www.ctan.org/pkg/siunitx). This implementation (modelled after the numpy support) is far from complete and I expect many corner cases which would need special attention. But before I put in more effort, I would like to hear if there is any interest in including this upstream.

Best regards,
Björn

### CODE REVIEW

**Comment by JelteF** [comment]
I have never used the quantities python package myself, but this integration seems cool. I will definitely merge it when you are finished with it. On suggestion btw, you can probably use the Command as a parent class for your quantity class.

**Comment by bjodah** [comment]
Cool, I'll try to change it to Command.

**Comment by JelteF** [comment]
Would you like to see this merged now, or should I wait until you have some more? 

If you want it merged now, could you squash the commits together into one big commit? Then I'll read that and check for other changes that might be needed. 
If you want to wait until you added more, just let me know again when you added more.

**Comment by bjodah** [comment]
You can merge it now. You may want to mark it "experimental" to indicate that it is still an immature module. (I was hoping to find some spare time the weekend that passed but I didn't, but as soon as I do I will add more tests).

**Comment by JelteF** [comment]
Am I correctly assuming that the function `dimensionality_to_siunitx` is an internal function? If that is the case, could you prepend it with an underscore? That way it will not be imported when using `from pylatex.quantities import *` and it will also not be shown in the documentation that I am currently writing.

And lastly, could you add the `Quantities` object API to the args test, so it is clear when the API changes in the future? https://github.com/JelteF/PyLaTeX/blob/master/tests/args.py

**Comment by bjodah** [comment]
You're correct. Made it private and added tests in tests/args.py
Let me know if I should rebase away the last commit.

**Comment by JelteF** [comment]
Looks great and yeah, please rebase it away.

**Comment by JelteF** [comment]
It seems like you haven't imported Quantity in the args test.

**Pull request merged**
