### PR TITLE
Added class SubFigure

### PR DESCRIPTION
**Pull request by ericvm**
Added class SubFigure for use with the subcaption package.

Also added an example in the examples folder.

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks for the pull request, at the moment I'm quite busy with my thesis. I will look this over and try to merge it in when I have time. One thing I saw with the quick look I just gave it. You added a new Added section in the changelog right above the one that was already there. Could you just add your bullet point to the already existing section?

**Comment by ericvm** [comment]
Done that!

**Comment by JelteF** [comment]
Could you squash those commits together?

**Comment by ericvm** [comment]
I tried to follow this (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). Not sure I dit it right, though.

**Comment by JelteF** [comment]
Something went wrong, and I think I know what. You probably had to pull again right? You should have used force push. 
You can do it right by now doing:

```
git reset HEAD^ --hard  # removes the merge commit that was caused by doing a git pull
git push -f
```

Then it should just have one commit with all the changes in it.

**Comment by ericvm** [comment]
Ok, seems right now. Thanks! :)

**Comment by JelteF** [comment]
Great, I'll start reading the actual code now :stuck_out_tongue_winking_eye:

**Comment by JelteF** [comment]
Looks great. It seems like mostly a copy of the Figure class, am I right? It might be useful to create a float base class, so functions can be reused and changed in all. But that is for some time in the future.

**Comment by ericvm** [comment]
I tried not to rewrite the Figure class and reuse it instead, but this was not possible without some disrupting changes. Therefore, I just copied the relevant parts from Figure into SubFigure.

Creating a base class common for both would be the best choice, I think.

**Pull request merged**
