### PR TITLE
Avoid rendering empty lists

### PR DESCRIPTION
**Pull request by ovaskevich**
LaTeX spits out an error if a list environment (i.e., itemize, enumerate) doesn't contain any items. This allows empty lists to be rendered without requiring the library user to have to check preemptively if the list content will be empty.

Wasn't able to test this just yet - sorry!

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks this seems like a good fix, but could you maybe add a test for this so it will not break again?

**Comment by JelteF** [comment]
Could you still do this?

**Comment by ovaskevich** [comment]
Just saw this. I merged changes and added a test. Wasn't sure where to update the changelog, though.

**Comment by JelteF** [comment]
The changelog can be found here now: 
https://github.com/JelteF/PyLaTeX/blob/master/docs/source/changelog.rst

**Comment by JelteF** [comment]
One more thing, could you rebase your changes on the current instead of merging them? Now it is really hard to see what actually changed because of the huge merge commit. And could you make `ommit_if_empty` a class variable instead of an instance variable. Then it does not have to be passed on through the `__init__` method.

**Comment by JelteF** [comment]
I just merged this myself with: 035c1e79d61ddcfdb2c35ce73e2c269f6063878d

Thank you for the effort anyway.

**Pull request closed without merging**
