### PR TITLE
Fix tilde, caret and backslash escaping

### PR DESCRIPTION
**Pull request by rutsky**
This is the rework of PR #32

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks great work, hadn't run in to the issues with those characters yet. Will merge when I have the time to test it out.

**Comment by rutsky** [comment]
How about I push fix for #33  in this PR, since fix depends on this branch?

**Comment by JelteF** [comment]
Sounds good

**Comment by rutsky** [comment]
I noticed that newline characters are not correctly escaped too: they were escaped as `\\\\` instead `\\`. 
Pushed commit that fixes this in current branch.

**Comment by JelteF** [comment]
Sorry for the delay, I was a bit busy lately.

**Pull request merged**
