### PR TITLE
Make paths work with jobname

### PR DESCRIPTION
**Pull request by Vayel**

### CODE REVIEW

**Comment by Vayel** [comment]
Oups, I didn't update the CHAGELOG.md. Should I add a commit for that or use `squash`?

**Comment by JelteF** [comment]
You can just use the squash command

**Comment by Vayel** [comment]
What about replacing `default_filename` by  `default_path`?

**Comment by JelteF** [comment]
I think  `default_filepath` would be best, since that shows the filename should be included as well.

**Comment by JelteF** [comment]
Could you fix the style error? And could you rebase this branch on master, so it can be automatically merged. (by running `git rebase master` when you are on your jobname branch)

**Comment by Vayel** [comment]
Should I add a commit to fix the second error?

```
Checking for code style errors 
pylatex/document.py:99:1: W293 blank line contains whitespace
pylatex/document.py:138:31: F821 undefined name 'filename'
```

**Comment by Vayel** [comment]
It appears to be ok.

**Comment by JelteF** [comment]
Thanks for all the changes

**Pull request merged**
