### PR TITLE
Vagrant support

### PR DESCRIPTION
**Pull request by sebastianhaas**
As I mentioned in #71 it can be quite a challenging task to set up a fully functional development environment for this project.

I created a Vagrantfile for that purpose. It will pop a minimal Ubuntu x64 box and then install only the required packages for this project.

How-to: (given that Vagrant is installed)
* ``vagrant up`` Will pop the VM and install all required software
* ``vagrant ssh`` Connect via ssh
* Inside the guest: e.g. run tests with ``cd /vagrant``, ``./testall.sh -p python3``

### CODE REVIEW

**Comment by JelteF** [comment]
This sounds good to have, I'm not sure I'm going to maintain it though.
Could you rebase this on master instead of merging it in?

**Comment by sebastianhaas** [comment]
Well the short answer is no, I cannot ;)

I have no clue what I did there but obviously rebasing caused some major trouble. I really don't know what to do know, and I don't have much time to figure it out right now so I probably it will take me quite a while to finish this just so you know :)

**Comment by JelteF** [comment]
I will just cherry pick your non merge commits. Which should probably work.

**Comment by sebastianhaas** [comment]
Should work. But keep in mind that nosetests3/nosetests switch isn't done yet which will break travis.

**Comment by JelteF** [comment]
Hmm, I just checked out the vagrant file. It seems to be ruby, although very simple ruby. Is it possible to change it to Python or just normal shell script? If not that's not possible with vagrant that's okay and ruby is fine, but I'd rather not use to much different languages in one library.

**Comment by sebastianhaas** [comment]
Nah I guess the Vagrantfile standard sticks to Ruby. :/
http://docs.vagrantup.com/v2/vagrantfile/ - see the third paragraph.

I could extract the provisioning part to an external shell script and remove all the unnecessary parts on the Ruby part. But that would make it two files for a feature probably not everyone is going to use so that's most likely not what you want to achieve.

**Comment by JelteF** [comment]
Nah, in that case this is fine.

**Comment by JelteF** [comment]
I'll merge this later then, because these commits seem to be a bit of a mess. If you can do that yourself that is fine as well and I can just simply merge it.

**Comment by sebastianhaas** [comment]
There is a good chance I get off from work tomorrow- in that case I will fix those three PRs tomorrow. If not, I guess some time in August.

**Comment by JelteF** [comment]
I have also merged this now, so I'm closing it.

**Pull request closed without merging**
