### PR TITLE
Fix dumps list mapper

### PR DESCRIPTION
**Pull request by klaplong**
Fixes https://github.com/JelteF/PyLaTeX/issues/159

### CODE REVIEW

**Comment by JelteF** [comment]
Could you use _latex_item_to_string to convert the mapped thing to a string? It handles more edge cases.

**Comment by klaplong** [comment]
What "mapped thing" do you mean?

**Comment by JelteF** [comment]
Your lambda thingy

**Comment by klaplong** [comment]
commit --amend I suppose?

**Comment by JelteF** [comment]
Merged it with a small edit, to handle the case of multiple mappers.

**Pull request merged**
