### PR TITLE
section.py : Add sectioning levels such as chapter

### PR DESCRIPTION
**Pull request by Wddysr**
Part, chapter and some other sectioning levels wasn't implemented,
these are usefull for some types of document such as report.

### CODE REVIEW

**Comment by dgrigonis** [comment]
Nice one. Once/if this is merged I will add label/ref implementation for these.

**Comment by Wddysr** [comment]
I'm already working on a generic label/ref implementation for PyLaTex, use it with sectioning is my main goal.

**Comment by dgrigonis** [comment]
I will leave it to you then. But can give you my implementation which I have not pushed yet:

```python
class RefLabelMixin(CommandBase):
    @classmethod
    def sec(cls, name):
        return cls(name, prefix='sec')

    @classmethod
    def sub(cls, name):
        return cls(name, prefix='sub')

    @classmethod
    def ssub(cls, name):
        return cls(name, prefix='ssub')

    @classmethod
    def fig(cls, name):
        return cls(name, prefix='fig')

    @classmethod
    def tab(cls, name):
        return cls(name, prefix='tab')

    @classmethod
    def theo(cls, name):
        return cls(name, prefix='theo')


class Label(RefLabelMixin):
    def __init__(self, name, prefix=''):
        name = '{}:{}'.format(prefix, name)
        super(Label, self).__init__(arguments=NoEscape(name))


class Ref(RefLabelMixin):
    def __init__(self, name, prefix=''):
        name = '{}:{}'.format(prefix, name)
        super(Ref, self).__init__(arguments=NoEscape(name))
```

Then just need to define `section` arguments, `dumps`, etc

**Comment by JelteF** [comment]
Looks like a great adition, but could you change it so that everything is a subclass of Section again to keep backwards compatible behaviour when the numbering default was changed.

**Comment by Wddysr** [comment]
Done

**Pull request merged**
