### PR TITLE
allow non-pdf matplotlib figures

### PR DESCRIPTION
**Pull request by dgrigonis**

### CODE REVIEW

**Comment by JelteF** [comment]
Looks reasonable, but could you add the extension kwarg explicitly between args and kwargs. Could you also add and document it inside add_plot. That way people can easily discover it. You can let it default to pdf.

**Comment by dgrigonis** [comment]
done.

**Comment by dgrigonis** [comment]
Also, when do you think you are going to release new version?

**Comment by JelteF** [comment]
Good question I'll try to release one this week.

**Pull request merged**
