### PR TITLE
Fix scripts for python3 use

### PR DESCRIPTION
**Pull request by sebastianhaas**
Currently, ``testall.sh`` and ``docs/create_doc_files.sh`` won't work in a ``python3`` environment.

The ``-p`` switch is present, but does not propagate to ``docs/create_doc_files.sh``. Also the use of ``nosetests`` in this context is wrong and should be replaced by ``nosetests3``.
This PR attempts to fix both issues.

Please note that atm there is a switch missing for the nosetests3/nosetests thingy... Need to fix that before a possible merge. Just wanted to make sure you're interested anyway.

### CODE REVIEW

**Comment by JelteF** [comment]
Hmm, this is really weird. I mostly use all the scripts just in python3 and fix things when Travis tells me Python 2 is broken. The nosetests3 thing might be correct, I just started using it today, but it seemed to work just fine in a venv with python3 only. Some things were broken a bit today, so maybe it was the old version that you used.

**Comment by JelteF** [comment]
Could you rebase this on master instead of merging it in?

**Comment by sebastianhaas** [comment]
See the other PR, no I can't right now. :p

Regarding the nosetests3 thingy- of course in a venv everything is fine. And of course you could also alias python3 to python- but then you don't need the -p switch at all. So I guess it's just about being consistent in that case.

**Comment by JelteF** [comment]
Ah, I read the pull request better now. The create_doc_files.sh change makes lots of sense.

The nosetests3 change seems to cause issues though, both on my machine in the venv and using Travis, since it is not installed. I will try to merge it in without those. Please make a separate pull request for the nosetests3 issue.

**Comment by sebastianhaas** [comment]
As I said before, one would have to make a switch depending on which python command is being used. Anyone with `python3` will also use `pip3` and `nosetests3` I guess. That's why it breaks on Travis, since you running it with `python`.

**Comment by sebastianhaas** [comment]
But sure, I'll make a separate PR for that if you want, although it is somehow really related to this enhancement. I guess if you merge it with the python3 option, but without the nosetests3 if-clause it won't work for python3 users either-

**Comment by JelteF** [comment]
Merged this without the nosetests3

**Pull request closed without merging**
