### PR TITLE
Rewriting "Library Usage" documentation.

### PR DESCRIPTION
**Pull request by rfilmyer**
While I use this module often, I have found a few ways to improve the documentation in order to make the package more user-friendly. To start, I rewrote the "Library Usage" section.

I haven't used a package with Sphinx before, so let me know if there are any additional changes I should make so that it appears as expected.

### CODE REVIEW

**Comment by rfilmyer** [comment]
I'll also squash commits, but I wanted to show you what I've done first.

**Comment by JelteF** [comment]
Wow thanks a lot. I'll read this over right away.

**Comment by rfilmyer** [comment]
No problem. I was going to expand a few other things when I got the chance,
but I didn't know how far along you were in refactoring.

**Comment by JelteF** [comment]
The refactoring is basically finished. I just haven't released because there were some open pull requests that I still had to merge and the documentation was not even close to being finished. I got a bit distracted though, so I haven't worked on those things for a while.

Furthermore, as you can see travis is complaining about some stuff. You should try running `testall.sh` with python 3, that way you can check for errors locally.

**Comment by JelteF** [comment]
I just read everything and I think you have done a good job in making it better readable. If you fix the warnings, change the two things I noted and squash all the commits together I will definitly merge it.

**Comment by rfilmyer** [comment]
Changed and squashed.

**Comment by JelteF** [comment]
I added the changes to your commit and fixed some other documentation errors as well. Thanks again for writing it.

**Comment by rfilmyer** [comment]
I see my changes have made it on to the main repository, so should I just close this PR?

**Comment by JelteF** [comment]
Done, forgot to do that.

**Pull request closed without merging**
