### PR TITLE
Add Plt class

### PR DESCRIPTION
**Pull request by Vayel**
Seems to work. **You should test it though**. `examples/plt.py` generates that:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{graphicx}
\title{}
\author{}
\date{}

\begin{document}
Introduction.
Take a look at this beautiful plot:
\begin{figure}[htbp]
\centering
\includegraphics[width=0.8\textwidth]{/home/vincent/Documents/Prog/PyLaTeX/tmp/plot}
\caption{I am a caption.}\end{figure}
Created using matplotlib.
Conclusion.
\end{document}
```

But the generated PDF is strange. Or maybe it isn't. I'm not an expert with LaTeX.

### CODE REVIEW

**Comment by Vayel** [comment]
You need to install matplotlib for Travis but I prefer you to edit the `.travis.yml` file.

**Comment by Vayel** [comment]
The following LaTeX code works:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{graphicx}
\title{}
\author{}
\date{}

\begin{document}
    Introduction.

    Take a look at this beautiful plot:

    \begin{figure}[htbp]
        \centering
        \includegraphics[width=0.8\textwidth]{/home/eleve/vincent.lefoulon/Documents/LaTeX/plot}
        \caption{I am a caption.}
    \end{figure}

    Created using matplotlib.

    Conclusion.
\end{document}
```

Will work on that.

**Comment by JelteF** [comment]
I have updated the .travis.yml to include matplotlib. Could you rebase on master to see if Travis doesn't fail now?

As for the issue you are seeing. I think both adding to the same paragraph and to a new one should be possible. I think a couple of keywords like end_paragraph, begin_paragraph would fix the problem. They might have different defaults for different types of objects. You would want them true for this one for instance but probably false in most other cases.

**Comment by Vayel** [comment]
Would you mind developing the use of `end_paragraph` and `begin_paragraph`?

**Comment by JelteF** [comment]
I have added it in there, just call super().__init__() with `seperate_paragraph=True`

**Comment by Vayel** [comment]
Instead of specifying `begin_paragraph` and `end_paragraph` arguments, what about having something like `doc.new_line()`?

**Comment by JelteF** [comment]
I think this solution is better, since you can default to a behaviour for
certain classes.

**Comment by Vayel** [comment]
OMG, what did I do with the history?

**Comment by JelteF** [comment]
It indeed looks quite wrong. If you are not able to figure out how to get
it back to normal, you can always cherry pick the good commits to a new
branch that is based on the current master.

**Pull request closed without merging**
