### PR TITLE
MultiColumn and MultiRow table classes added

### PR DESCRIPTION
**Pull request by Rsullivan00**
For issue #4:

What do you think about something like this for the multicolumn support? This approach lets us put the multicolumn in any part of a table like this:

    table1 = Table('|c|c|c|c|')
    table1.add_hline()
    table1.add_row((1, 2, 3, 4))
    table1.add_hline()
    row_cells = ('9', MultiColumn(3, '|c|', 'Multicolumn not on left'))
    table1.add_row(row_cells)
    table1.add_hline()

### CODE REVIEW

**Comment by JelteF** [comment]
Sorry for not responding quickly. At the moment I'm quite busy however with my thesis and I can't seem to find a lot of time.

Thanks for the pull request, it looks I'm quite good with the quick look I gave it. It is quite big however, so it could take a while before I have the time to thoroughly look it over. One simple thing, could you rebase your branch on the current master, that way it can be merged more easily.

**Comment by Rsullivan00** [comment]
I'm still a bit of a novice with git, but I think I have it in a state to be easily merged.

There's no rush to merge it; take your time looking at my changes.

**Comment by fariza** [comment]
Hello, just a thought, why don't just add indexing support for the table?

**Comment by JelteF** [comment]
You're commit looks very weird now. It contains a lot of changes from other commits as well, like the filename->filepath change.

@fariza This sounds very cool, it might be quite hard to implement in a sane way, especially for multirow/multicol.

**Comment by JelteF** [comment]
Once you change the content variable thing I can rebase it in the correct way and merge it into the repository. Just commit that change on top of it. Then I will fix the git stuff.

**Comment by JelteF** [comment]
Again, thanks for the pull request. I have now merged it in with some changes.

**Comment by Rsullivan00** [comment]
Thanks for fixing the remaining issues! I've been busy finishing up school projects for the last week or so.

**Pull request closed without merging**
