### PR TITLE
Use \[ .. \] for display math instead of $$ ... $$

### PR DESCRIPTION
**Pull request by TorbjornT**
$$ .. $$ is not recommended for use with LaTeX, see http://tex.stackexchange.com/questions/503

I don't know if that is the best way of generating the correct strings though, please advise if there is a better way.

### CODE REVIEW

**Comment by JelteF** [comment]
Good call, I did not know about this.

A couple of things:
- Can you merge the two string literals on both sides like this: `'\\[%\n'`?
- Can you add the amsmath package like it is done now for the matrix environment?
- Can you add a entry in the changelog?

**Comment by TorbjornT** [comment]
Damn, sorry about the bad Markdown in the changelog, I'm so used to Stackexchange where you only need one backtick.

**Comment by JelteF** [comment]
Could you undo the changes to the changelog in lines other than the one you added. Single backticks are for links to API reference pages, double backticks are for regular verbatim text (like the latex snippets in your line).

**Comment by JelteF** [comment]
Thanks for the contribution merged it into master

**Pull request closed without merging**
