### PR TITLE
Introduced error handling when adding table rows of mismatching size,…

### PR DESCRIPTION
**Pull request by BeckmaR**
I made a little error check on adding rows to table, because LaTeX actually doesn't like table rows with the wrong number of cells. I don't know if you like the way I did it, but as far as I can see, it does what it should. Also, I fixed the example in the readme, because I did not work for me:
When you append some text and an italic at the same time, thats str + NoEscape, which delivers a str, so the latex command for italic will be escaped again later, which does not work. Also, when you try to display special chars, you should not append them with latex escape, as they are then escaped two times, so \& becomes \textbackslash{}\\& or something alike.
You actually didn't do it this way in your example folder, so maybe you forgot to change it or something?

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks for the pull request. It looks very good! I added some comments for small changes that I'd like to see before merging this.

**Comment by JelteF** [comment]
One more thing, could you add an entry to the changelog to show that this feature was added?

**Comment by BeckmaR** [comment]
The second commit failed because a line was too long (did not run testall.sh, shame on me). The third commit passed testall.sh, but travis seems to have some other problem.

**Comment by JelteF** [comment]
It seems there was a random error in the build. I restarted it. Could you
also squash all the commits together if you fixed the little issues. Then
I'll merge it in.

**Comment by BeckmaR** [comment]
Done.

**Comment by JelteF** [comment]
Sorry, when I looked over the code again I had some additional nitpicks. If you fix those as well and squash the commits again I will merge those. The rest looks great though.

**Comment by BeckmaR** [comment]
Everything done.

**Comment by JelteF** [comment]
Thanks for the pull request and all the changes. It's merged now. :)

**Pull request merged**
