### PR TITLE
raise a descriptive error when no compiler is installed

### LINKED ISSUE #158: More specific exception when pdflatex and latexmk are missing
Working on Windows, when neither pdflatex, nor latexmk can be called, the general WindowsError is raised:

    WindowsError: [Error 2] The system cannot find the file specified

because it is the result of a failed `subprocess.check_output()` shell call.  This is easily mistaken for a missing user file (.tex file, etc.), and it requires some digging into the pylatex code to determine that this is due to a missing latex utility.   The exception is raised in `def generate_pdf` of `class Document` in `document.py` here:

    304         else:
    305             # If none of the compilers worked, raise the last error
    306             raise(os_error)

Could a new exception type be added to make this problem easier to debug?  :

### PR DESCRIPTION
**Pull request by HassenPy**
should fix #158

### CODE REVIEW

**Comment by HassenPy** [comment]
tests failing due to https://github.com/python-quantities/python-quantities/issues/129

**Comment by JelteF** [comment]
Thanks for the PR I'll try to fix travis this weekend and I'll merge it after the tests pass.

**Comment by JelteF** [comment]
Master is now fixed, could you merge it with this branch? I'd like to see the tests passing before I merge it. Code looks fine though.

**Comment by HassenPy** [comment]
done i guess

**Comment by JelteF** [comment]
Alright, thanks!

**Pull request merged**
