### PR TITLE
Plot

### PR DESCRIPTION
**Pull request by Vayel**
See [here](https://github.com/JelteF/PyLaTeX/pull/37#issuecomment-80655963).

### CODE REVIEW

**Comment by JelteF** [comment]
I have tested it and it looks really good. Great work. One small thing though. Could you setup your editor to make the tabs  4 spaces and to remove trailing whitespace. That way I won't have to do a whitespace only commit the next time.

**Comment by JelteF** [comment]
Fixes #35

**Comment by Vayel** [comment]
That's weird for the spaces. Would you have an example where a tab is not 4 spaces?

**Comment by JelteF** [comment]
Of if you already set that it's probably nowhere. Then it's just the
trailing whitespaces.

**Comment by Vayel** [comment]
Do you want me to do a commit to fix that?

**Comment by JelteF** [comment]
Nah, I already did.

**Pull request merged**
