### PR TITLE
Float funcitonality

### PR DESCRIPTION
**Pull request by jbzdak**
This depends on HenryII pull request for python2 compatibility (I added some changes to this). 

Following features were added: 

1. Options class that holds options (both positional ones and key-value ones)
2. Dimension class (for representing latex dimensions) 
3. Latex classes that render themselves via jinja2 templates
4. Supprt for floats, subfloats and graphics.

### CODE REVIEW

**Comment by sebastianhaas** [comment]
Is there a way I can help out on this? I need to use options and dimensions and I'd rather help to get this ready for a merge than using my own fork.

**Comment by JelteF** [comment]
I haven't really had the need for this yet and I don't think this pull request will come alive any time soon. If you make a new pull request however, I would gladly take the time to merge it. You could try to take a look at the this one and take what needed, but it seems quite full with jinja stuff so only take the necessary parts.

**Comment by sebastianhaas** [comment]
Thank you for your quick reply. I'll try to familiarise with the subject and provide a PR in the next days.

**Comment by JelteF** [comment]
I wil close this one since its quite old, please open another pull request for stuff similar to this.

**Pull request closed without merging**
